### ISSUE TITLE
Latest java update breaks image

### ISSUE THREAD

**Issue by agutl** [payara/docker-payaraserver-full#56] opened 2018-11-05 12:34 UTC
I build my images based on payara/server-full:5.183. Usually I first apply all system updates which now contain a java update (`8u181-b13-1~deb9u1` to `8u181-b13-2~deb9u1`). This somehow breaks payara.

> $ bin/asadmin --user admin --passwordfile=/opt/pwdfile disable-phone-home
> NCLS-ADMIN-00010
> javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
> Command disable-phone-home failed.

server.log is full of:
`[Payara 5.183] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1541419956061] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:862)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:245)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1077)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1017)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1014)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1497)
	at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:250)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:683)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:598)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:310)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]`

Without updating java everything runs fine.

**Comment by pioneer2k** [comment] 2018-11-05 13:12
You can also reproduce this with payara/server-full:5-SNAPSHOT which comes with this JDK:
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

I think this is related to this fix for Payara on JDK 8u191:
https://github.com/payara/Payara/issues/3284
Looks like this fix is not working on 8u181

**Comment by MattGill98** [comment] 2018-11-05 14:51
Hi @agutl,

This issue is a duplicate of the above issue (thanks @pioneer2k). I'll close this issue.

Kind regards,

Matt

**Comment by pioneer2k** [comment] 2018-11-08 08:50
Hi @MattGill98 ,

I think you misunderstood something.
This is not a duplicate issue. It is a new issue, because the other issue states, that the error is fixed for Java 8u191, but the error still exists with Java 8u181. And because the Payara Docker Image comes with Java 8u181 this issue still exists. I just linked the other issue because it is related, but not the same.

Till this day the current Payara 5-SNAPSHOT image is not working for me.

**Comment by MattGill98** [comment] 2018-11-08 09:17
Hi @pioneer2k,

Thank you for pointing that out! My apologies, this does seem to be related but not a duplicate. I've reopened it!

Kind regards,

Matt

**Comment by smillidge** [comment] 2018-11-19 13:56
I think I read somewhere that the Debian u181 has the braking change in u191 downported. Just to make life complicated!

**Comment by MattGill98** [comment] 2018-11-21 10:52
Fixed in https://github.com/payara/docker-payaraserver-full/pull/59. Will be updating for other tags soon.

**Closed by MattGill98** 2018-11-21 10:52 UTC
